// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viaggiatore.Data;

#nullable disable

namespace Viaggiatore.Migrations
{
    [DbContext(typeof(ViaggioContext))]
    [Migration("20220524141953_tabellaRichiestaUtentiNewConTabella")]
    partial class tabellaRichiestaUtentiNewConTabella
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Viaggiatore.Models.Pacchetto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<double>("Prezzo")
                        .HasColumnType("float");

                    b.Property<string>("descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("immagine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("pacchetti");
                });

            modelBuilder.Entity("Viaggiatore.Models.RichiestaUtente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("PacchettoId")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasMaxLength(75)
                        .HasColumnType("int");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.HasIndex("PacchettoId");

                    b.ToTable("richiesteUtenti");
                });

            modelBuilder.Entity("Viaggiatore.Models.RichiestaUtente", b =>
                {
                    b.HasOne("Viaggiatore.Models.Pacchetto", "pacchetti")
                        .WithMany("richiesteUtenti")
                        .HasForeignKey("PacchettoId");

                    b.Navigation("pacchetti");
                });

            modelBuilder.Entity("Viaggiatore.Models.Pacchetto", b =>
                {
                    b.Navigation("richiesteUtenti");
                });
#pragma warning restore 612, 618
        }
    }
}
